OPINION_DELTAS.TO_HATED = {
    relationship_delta = 
    {
        [RELATIONSHIP.LOVED] = RELATIONSHIP.NEUTRAL,
        [RELATIONSHIP.LIKED] = RELATIONSHIP.NEUTRAL,
        [RELATIONSHIP.NEUTRAL] = RELATIONSHIP.DISLIKED,
        [RELATIONSHIP.DISLIKED] = RELATIONSHIP.HATED,
    },
    desc = "-> Toward Hated",
}