--THIS FILE IS AUTOGENERATED BY THE EDITOR. DO NOT CHANGE MANUALLY
return {
  layers = {
    {
      elements = {
        {
          hidden_in_editor = true,
          id = 1,
          img = "skies/TEMPLATE_ROAD_CONVO_FIGHT_SKY.tex",
          lock = false,
          node_type = "IMAGE",
          plax_flags = 31,
          scale = 0.68000000715256,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 562,
          y = -70
        },
        {
          hidden_in_editor = false,
          id = 2,
          img = "skies/Sky_Night_Generic_Flat.tex",
          night_colour = {
            highlights = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            midtones = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            shadows = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            }
          },
          night_colour_ignore_parent = true,
          node_type = "IMAGE",
          plax_flags = 115,
          scale = 1.0,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 524,
          y = 48
        },
        {
          hidden_in_editor = false,
          id = 3,
          img = "skies/BOG_sky_night2_CLOUD1.tex",
          night_colour = {
            highlights = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            midtones = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            shadows = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            }
          },
          night_colour_ignore_parent = true,
          node_type = "IMAGE",
          plax_flags = 115,
          scale = 0.5,
          tint_a = 218,
          tint_b = 146,
          tint_g = 146,
          tint_r = 146,
          uspeed = 0.0060000000521541,
          vspeed = 0.0,
          x = 550,
          y = -128
        },
        {
          bloom = 0.13199999928474,
          flip = true,
          hidden_in_editor = false,
          id = 4,
          img = "skies/Colonylands_Evening_moons.tex",
          night_colour = {
            highlights = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            midtones = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            shadows = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            }
          },
          night_colour_ignore_parent = true,
          node_type = "IMAGE",
          plax_flags = 115,
          scale = 0.5,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 186,
          y = 3
        },
        {
          hidden_in_editor = false,
          id = 5,
          img = "skies/BOG_sky_night2_CLOUD5.tex",
          night_colour = {
            highlights = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            midtones = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            shadows = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            }
          },
          night_colour_ignore_parent = true,
          node_type = "IMAGE",
          plax_flags = 115,
          scale = 0.5,
          uspeed = 0.0010000000474975,
          vspeed = 0.0,
          x = 574,
          y = 304
        },
        {
          hidden_in_editor = false,
          id = 6,
          img = "skies/BOG_sky_night2_CLOUD4.tex",
          night_colour = {
            highlights = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            midtones = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            shadows = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            }
          },
          night_colour_ignore_parent = true,
          node_type = "IMAGE",
          plax_flags = 115,
          scale = 0.5,
          tint_a = 239,
          tint_b = 255,
          tint_g = 255,
          tint_r = 255,
          uspeed = 0.0020000000949949,
          vspeed = 0.0,
          x = 413,
          y = 543
        },
        {
          hidden_in_editor = false,
          id = 7,
          img = "skies/BOG_sky_night2_CLOUD3.tex",
          night_colour = {
            highlights = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            midtones = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            shadows = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            }
          },
          node_type = "IMAGE",
          plax_flags = 115,
          scale = 0.5,
          tint_a = 239,
          tint_b = 255,
          tint_g = 255,
          tint_r = 255,
          uspeed = 0.003000000026077,
          vspeed = 0.0,
          x = 1262,
          y = 513
        },
        {
          hidden_in_editor = false,
          id = 8,
          img = "skies/BOG_sky_night2_CLOUD2.tex",
          night_colour = {
            highlights = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            midtones = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            shadows = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            }
          },
          night_colour_ignore_parent = true,
          node_type = "IMAGE",
          plax_flags = 115,
          scale = 0.5,
          tint_a = 220,
          tint_b = 255,
          tint_g = 255,
          tint_r = 255,
          uspeed = 0.0040000001899898,
          vspeed = 0.0,
          x = 914,
          y = 433
        },
        {
          hidden_in_editor = false,
          id = 9,
          img = "skies/BOG_sky_day1_BG.tex",
          node_type = "IMAGE",
          plax_flags = 103,
          scale = 0.5,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 580,
          y = 166
        },
        {
          hidden_in_editor = false,
          id = 10,
          img = "skies/BOG_sky_day3_CLOUD1.tex",
          node_type = "IMAGE",
          plax_flags = 103,
          scale = 0.5,
          tint_a = 200,
          tint_b = 255,
          tint_g = 255,
          tint_r = 255,
          uspeed = 0.0040000001899898,
          vspeed = 0.0,
          x = 557,
          y = 257
        },
        {
          hidden_in_editor = false,
          id = 11,
          img = "skies/BOG_sky_day3_CLOUD2.tex",
          node_type = "IMAGE",
          plax_flags = 103,
          scale = 0.5,
          tint_a = 215,
          tint_b = 255,
          tint_g = 255,
          tint_r = 255,
          uspeed = 0.003000000026077,
          vspeed = 0.0,
          x = 581,
          y = 282
        },
        {
          hidden_in_editor = false,
          id = 12,
          img = "skies/BOG_sky_day3_CLOUD3.tex",
          node_type = "IMAGE",
          plax_flags = 103,
          scale = 0.5,
          tint_a = 221,
          tint_b = 255,
          tint_g = 255,
          tint_r = 255,
          uspeed = 0.0020000000949949,
          vspeed = 0.0,
          x = 565,
          y = 341
        },
        {
          hidden_in_editor = false,
          id = 13,
          img = "skies/BOG_sky_day3_CLOUD4.tex",
          node_type = "IMAGE",
          plax_flags = 103,
          scale = 0.5,
          tint_a = 230,
          tint_b = 255,
          tint_g = 255,
          tint_r = 255,
          uspeed = 0.0010000000474975,
          vspeed = 0.0,
          x = 579,
          y = 268
        },
        {
          hidden_in_editor = false,
          id = 14,
          img = "skies/BOG_sky_day3_CLOUD5.tex",
          node_type = "IMAGE",
          plax_flags = 103,
          scale = 0.5,
          tint_a = 240,
          tint_b = 255,
          tint_g = 255,
          tint_r = 255,
          uspeed = 0.00050000002374873,
          vspeed = 0.0,
          x = 558,
          y = 335
        },
        {
          bloom = 0.041000001132488,
          hidden_in_editor = false,
          id = 15,
          img = "skies/BOG_sky_day1_MOONS01.tex",
          node_type = "IMAGE",
          plax_flags = 103,
          scale = 0.5,
          uspeed = 0.0,
          vspeed = 0.0,
          x = -294,
          y = 52
        }
      },
      name = "FBG",
      plax = 0.5,
      plax_flags = 127
    },
    {
      elements = {},
      name = "BG",
      plax = 0.5,
      plax_flags = 127
    },
    {
      elements = {
        {
          hidden_in_editor = false,
          id = 18,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01__RESINTERIOR_MG_main.tex",
          lock = true,
          node_type = "IMAGE",
          plax_flags = 127,
          scale = 0.5,
          x = 595,
          y = -85
        },
        {
          flip = true,
          id = 19,
          name = "CHARACTER",
          node_type = "SLOT",
          plax_flags = 119,
          posedef = "sit_at_table_back",
          preview_agent = "ROOK",
          priority = 2,
          scale = 0.31999999284744,
          x = -320,
          y = -330
        },
        {
          bloom = 0.19099999964237,
          hidden_in_editor = false,
          id = 20,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01_MG_LAMPS_YELLOW.tex",
          node_type = "IMAGE",
          plax_flags = 119,
          scale = 0.5,
          tint_a = 255,
          tint_b = 98,
          tint_g = 169,
          tint_r = 238,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 594,
          y = -85
        },
        {
          bloom = 0.28600001335144,
          hidden_in_editor = false,
          id = 21,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01_MG_LIGHTS_ORANGE.tex",
          node_type = "IMAGE",
          plax_flags = 119,
          scale = 0.5,
          tint_a = 255,
          tint_b = 79,
          tint_g = 143,
          tint_r = 250,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 595,
          y = -85
        },
        {
          bloom = 0.20900000631809,
          hidden_in_editor = false,
          id = 22,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01_MG_MICROWAVE1.tex",
          node_type = "IMAGE",
          plax_flags = 119,
          scale = 0.5,
          tint_a = 56,
          tint_b = 58,
          tint_g = 136,
          tint_r = 184,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 595,
          y = -85
        },
        {
          bloom = 0.25499999523163,
          hidden_in_editor = false,
          id = 23,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01_MG_MICROWAVE2.tex",
          node_type = "IMAGE",
          plax_flags = 119,
          scale = 0.5,
          tint_a = 201,
          tint_b = 151,
          tint_g = 234,
          tint_r = 111,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 595,
          y = -85
        },
        {
          bloom = 0.15899999439716,
          hidden_in_editor = false,
          id = 24,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01_MG_SCREENS_BLUE.tex",
          node_type = "IMAGE",
          plax_flags = 119,
          scale = 0.5,
          tint_a = 183,
          tint_b = 215,
          tint_g = 192,
          tint_r = 88,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 595,
          y = -85
        },
        {
          bloom = 0.20499999821186,
          hidden_in_editor = false,
          id = 25,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01_MG_STUFF_BLUE.tex",
          node_type = "IMAGE",
          plax_flags = 119,
          scale = 0.5,
          tint_a = 255,
          tint_b = 119,
          tint_g = 241,
          tint_r = 213,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 595,
          y = -85
        },
        {
          anim = "character",
          anim_phase = 0.0,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 100.0,
          animfile = "anim/bar_atmo_glow.zip",
          blend_mode = 8,
          bloom = 0.18199999630451,
          hidden_in_editor = false,
          id = 26,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 119,
          scale = 0.10000000149012,
          tint_a = 177,
          tint_b = 254,
          tint_g = 252,
          tint_r = 140,
          x = 438,
          y = -29
        },
        {
          blend_mode = 8,
          bloom = 0.086000002920628,
          hidden_in_editor = false,
          id = 27,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01_MG_STOVE_LIGHT.tex",
          node_type = "IMAGE",
          plax_flags = 119,
          scale = 0.5,
          tint_a = 193,
          tint_b = 111,
          tint_g = 217,
          tint_r = 251,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 594,
          y = -85
        },
        {
          hidden_in_editor = false,
          id = 28,
          name = "PARTICLES",
          node_type = "PARTICLES",
          particles = "steam_cooking",
          plax_flags = 119,
          scale = 0.23000000417233,
          tint_a = 255,
          tint_b = 217,
          tint_g = 228,
          tint_r = 249,
          x = 675,
          y = -54
        },
        {
          hidden_in_editor = false,
          id = 29,
          name = "PARTICLES",
          node_type = "PARTICLES",
          particles = "waterfall",
          plax_flags = 119,
          scale = 0.10999999940395,
          tint_a = 32,
          tint_b = 255,
          tint_g = 255,
          tint_r = 255,
          x = 923,
          y = -88
        },
        {
          hidden_in_editor = false,
          id = 30,
          name = "PARTICLES",
          node_type = "PARTICLES",
          particles = "steam_vent_floor",
          plax_flags = 119,
          scale = 0.40999999642372,
          x = 787,
          y = -81
        },
        {
          anim = "character",
          anim_phase = 17.273000717163,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 70.908996582031,
          animfile = "anim/bar_atmo_glow.zip",
          blend_mode = 8,
          hidden_in_editor = false,
          id = 31,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 119,
          scale = 0.11999999731779,
          tint_a = 106,
          tint_b = 106,
          tint_g = 214,
          tint_r = 241,
          x = 375,
          y = 196
        },
        {
          anim = "character",
          anim_phase = 5.0,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 100.0,
          animfile = "anim/fx_bar_atmo_glow.zip",
          blend_mode = 8,
          bloom = 0.0,
          day_colour = {
            highlights = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            midtones = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            shadows = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            }
          },
          hidden_in_editor = false,
          id = 32,
          lock = false,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 127,
          scale = 0.15000000596046,
          tint_a = 100,
          tint_b = 143,
          tint_g = 245,
          tint_r = 255,
          x = 438,
          y = 170
        },
        {
          anim = "character",
          anim_phase = 24.545000076294,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 85.908996582031,
          animfile = "anim/bar_atmo_glow.zip",
          blend_mode = 8,
          hidden_in_editor = false,
          id = 33,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 119,
          scale = 0.079999998211861,
          tint_a = 106,
          tint_b = 106,
          tint_g = 214,
          tint_r = 241,
          x = 490,
          y = 257
        },
        {
          anim = "character",
          anim_phase = 5.0,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 100.0,
          animfile = "anim/fx_bar_atmo_glow.zip",
          blend_mode = 8,
          bloom = 0.0,
          day_colour = {
            highlights = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            midtones = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            shadows = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            }
          },
          hidden_in_editor = false,
          id = 34,
          lock = false,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 127,
          scale = 0.18999999761581,
          tint_a = 100,
          tint_b = 143,
          tint_g = 245,
          tint_r = 255,
          x = 187,
          y = 198
        },
        {
          anim = "fx",
          anim_phase = 45.909000396729,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 100.0,
          animfile = "anim/bar_atmo_flies.zip",
          blend_mode = 8,
          bloom = 0.050000000745058,
          hidden_in_editor = false,
          id = 35,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 119,
          scale = 0.80000001192093,
          tint_a = 255,
          tint_b = 107,
          tint_g = 255,
          tint_r = 221,
          x = -174,
          y = 16
        },
        {
          anim = "fx",
          anim_phase = 0.0,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 100.0,
          animfile = "anim/bar_atmo_flies.zip",
          blend_mode = 8,
          hidden_in_editor = false,
          id = 36,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 119,
          rot = 1.4500000476837,
          scale = 0.64999997615814,
          tint_a = 255,
          tint_b = 107,
          tint_g = 255,
          tint_r = 221,
          x = 192,
          y = 211
        },
        {
          anim = "fx",
          anim_phase = 65.908996582031,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 100.0,
          animfile = "anim/bar_atmo_flies.zip",
          blend_mode = 8,
          hidden_in_editor = false,
          id = 37,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 119,
          scale = 0.8299999833107,
          tint_a = 255,
          tint_b = 107,
          tint_g = 255,
          tint_r = 221,
          x = -698,
          y = 47
        },
        {
          anim = "character",
          anim_phase = 5.0,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 139.09100341797,
          animfile = "anim/fx_bar_atmo_glow.zip",
          blend_mode = 8,
          bloom = 0.0,
          day_colour = {
            highlights = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            midtones = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            shadows = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            }
          },
          hidden_in_editor = false,
          id = 38,
          lock = false,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 127,
          scale = 0.10000000149012,
          tint_a = 117,
          tint_b = 54,
          tint_g = 138,
          tint_r = 241,
          x = 737,
          y = 2
        },
        {
          anim = "flickering_glow",
          anim_phase = 0.0,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 100.0,
          animfile = "anim/flickering_glow_fx.zip",
          blend_mode = 8,
          hidden_in_editor = false,
          id = 39,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 119,
          rot = 1.5599999427795,
          scale = 0.37999999523163,
          tint_a = 158,
          tint_b = 242,
          tint_g = 219,
          tint_r = 176,
          x = 1623,
          y = -43
        },
        {
          anim = "flickering_glow",
          anim_phase = 0.0,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 100.0,
          animfile = "anim/flickering_glow_fx.zip",
          blend_mode = 8,
          hidden_in_editor = false,
          id = 40,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 119,
          rot = 1.5599999427795,
          scale = 0.14000000059605,
          tint_a = 188,
          tint_b = 111,
          tint_g = 235,
          tint_r = 239,
          x = 579,
          y = 19
        },
        {
          hidden_in_editor = false,
          id = 41,
          name = "PARTICLES",
          node_type = "PARTICLES",
          particles = "pollen",
          plax_flags = 119,
          scale = 0.81000000238419,
          tint_a = 113,
          tint_b = 255,
          tint_g = 255,
          tint_r = 255,
          x = -23,
          y = 49
        },
        {
          hidden_in_editor = true,
          id = 42,
          name = "PARTICLES",
          node_type = "PARTICLES",
          particles = "pollen",
          plax_flags = 119,
          scale = 0.81000000238419,
          tint_a = 113,
          tint_b = 255,
          tint_g = 255,
          tint_r = 255,
          x = 1274,
          y = -145
        },
        {
          hidden_in_editor = false,
          id = 43,
          name = "PARTICLES",
          node_type = "PARTICLES",
          particles = "dust_falling",
          plax_flags = 119,
          tint_a = 41,
          tint_b = 255,
          tint_g = 255,
          tint_r = 255,
          x = 587,
          y = 117
        },
        {
          hidden_in_editor = false,
          id = 44,
          lock = false,
          name = "PARTICLES",
          node_type = "PARTICLES",
          particles = "fog_screen_overlay",
          plax_flags = 119,
          scale = 0.69999998807907,
          tint_a = 74,
          tint_b = 192,
          tint_g = 214,
          tint_r = 149,
          x = 1251,
          y = -485
        },
        {
          hidden_in_editor = false,
          id = 45,
          lock = false,
          name = "PARTICLES",
          node_type = "PARTICLES",
          particles = "fog_screen_overlay",
          plax_flags = 119,
          scale = 0.69999998807907,
          tint_a = 74,
          tint_b = 144,
          tint_g = 186,
          tint_r = 89,
          x = 461,
          y = -496
        },
        {
          hidden_in_editor = false,
          id = 46,
          lock = false,
          name = "PARTICLES",
          node_type = "PARTICLES",
          particles = "fog_screen_overlay",
          plax_flags = 119,
          scale = 0.69999998807907,
          tint_a = 74,
          tint_b = 159,
          tint_g = 210,
          tint_r = 113,
          x = 1582,
          y = -288
        },
        {
          id = 47,
          name = "CHARACTER",
          node_type = "SLOT",
          plax_flags = 119,
          posedef = "bar_tending",
          preview_agent = "ROOK",
          priority = 1,
          scale = 0.18999999761581,
          x = 764,
          y = -262
        },
        {
          id = 48,
          name = "CHARACTER",
          node_type = "SLOT",
          plax_flags = 119,
          posedef = "lean",
          preview_agent = "ROOK",
          priority = 3,
          scale = 0.20000000298023,
          x = 333,
          y = -256
        },
        {
          flip = true,
          id = 49,
          name = "CHARACTER",
          node_type = "SLOT",
          plax_flags = 119,
          preview_agent = "ROOK",
          priority = 3,
          scale = 0.28999999165535,
          x = 552,
          y = -416
        },
        {
          id = 67,
          name = "CHARACTER",
          node_type = "SLOT",
          plax_flags = 119,
          preview_agent = "ROOK",
          priority = 3,
          scale = 0.30000001192093,
          x = -90,
          y = -401
        }
      },
      name = "MG",
      plax = 69.375,
      plax_flags = 127
    },
    {
      elements = {
        {
          flip = true,
          id = 51,
          name = "CHARACTER",
          node_type = "SLOT",
          plax_flags = 119,
          posedef = "sit_at_table_lean",
          preview_agent = "ROOK",
          priority = 1,
          scale = 0.55000001192093,
          x = 81,
          y = -633
        },
        {
          hidden_in_editor = false,
          id = 52,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01_FG_fightBR.tex",
          node_type = "IMAGE",
          plax_flags = 55,
          scale = 0.5799999833107,
          x = 180,
          y = -217
        },
        {
          hidden_in_editor = false,
          id = 53,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01_FG_fightBL.tex",
          node_type = "IMAGE",
          plax_flags = 55,
          scale = 0.63999998569489,
          x = 1012,
          y = -79
        },
        {
          anim = "idle",
          anim_phase = 0.0,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 100.0,
          animfile = "anim/chagger_smoke.zip",
          hidden_in_editor = false,
          id = 54,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 87,
          scale = 1.3799999952316,
          x = 1773,
          y = -470
        },
        {
          hidden_in_editor = false,
          id = 55,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01__RESINTERIOR_FG_bottomrightt.tex",
          lock = true,
          node_type = "IMAGE",
          plax_flags = 87,
          scale = 0.5,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 601,
          y = -101
        },
        {
          hidden_in_editor = false,
          id = 56,
          lock = false,
          name = "PARTICLES",
          node_type = "PARTICLES",
          particles = "fog_screen_overlay",
          plax_flags = 119,
          scale = 0.69999998807907,
          tint_a = 142,
          tint_b = 212,
          tint_g = 255,
          tint_r = 169,
          x = -633,
          y = -495
        },
        {
          hidden_in_editor = false,
          id = 57,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01__RESINTERIOR_FG_bottomleft.tex",
          lock = true,
          node_type = "IMAGE",
          plax_flags = 95,
          scale = 0.5,
          x = 595,
          y = -5
        },
        {
          bloom = 0.1140000000596,
          hidden_in_editor = false,
          id = 58,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01_FG_light_bottomleft.tex",
          node_type = "IMAGE",
          plax_flags = 87,
          scale = 0.5,
          tint_a = 201,
          tint_b = 131,
          tint_g = 199,
          tint_r = 255,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 595,
          y = -5
        },
        {
          anim = "character",
          anim_phase = 62.727001190186,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 128.18200683594,
          animfile = "anim/fx_bar_atmo_glow.zip",
          blend_mode = 8,
          bloom = 0.0,
          day_colour = {
            highlights = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            midtones = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            shadows = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            }
          },
          hidden_in_editor = false,
          id = 59,
          lock = false,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 95,
          scale = 0.17000000178814,
          tint_a = 90,
          tint_b = 210,
          tint_g = 242,
          tint_r = 255,
          x = 30,
          y = -276
        },
        {
          hidden_in_editor = false,
          id = 60,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01__RESINTERIOR_FG_topleft.tex",
          lock = false,
          node_type = "IMAGE",
          plax_flags = 95,
          scale = 0.5,
          x = 595,
          y = -145
        },
        {
          hidden_in_editor = false,
          id = 61,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01__RESINTERIOR_FG_toprightt.tex",
          lock = false,
          node_type = "IMAGE",
          plax_flags = 95,
          scale = 0.5,
          x = 595,
          y = -145
        },
        {
          bloom = 0.34999999403954,
          hidden_in_editor = false,
          id = 62,
          img = "plax/INT_WorkCamp_Domicile_01/INT_WorkCamp_Domicile_01_FG_light_bottomright.tex",
          node_type = "IMAGE",
          plax_flags = 87,
          scale = 0.5,
          tint_a = 144,
          tint_b = 91,
          tint_g = 154,
          tint_r = 255,
          uspeed = 0.0,
          vspeed = 0.0,
          x = 600,
          y = -102
        },
        {
          hidden_in_editor = false,
          id = 63,
          name = "PARTICLES",
          node_type = "PARTICLES",
          particles = "pollen",
          plax_flags = 119,
          scale = 0.99000000953674,
          tint_a = 111,
          tint_b = 255,
          tint_g = 255,
          tint_r = 255,
          x = 977,
          y = 859
        },
        {
          hidden_in_editor = false,
          id = 64,
          name = "PARTICLES",
          node_type = "PARTICLES",
          particles = "steam_cooking",
          plax_flags = 87,
          scale = 1.6299999952316,
          tint_a = 150,
          tint_b = 195,
          tint_g = 228,
          tint_r = 248,
          x = 1725,
          y = -504
        },
        {
          anim = "character",
          anim_phase = 62.727001190186,
          anim_repeat_delay_max = 0.0,
          anim_repeat_delay_min = 0.0,
          anim_speed = 128.18200683594,
          animfile = "anim/fx_bar_atmo_glow.zip",
          blend_mode = 8,
          bloom = 0.0,
          day_colour = {
            highlights = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            midtones = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            },
            shadows = {
              colour = {
                1,
                1,
                1
              },
              hsv = {
                0,
                1,
                1
              }
            }
          },
          hidden_in_editor = false,
          id = 65,
          lock = false,
          name = "ANIM",
          node_type = "ANIMATION",
          plax_flags = 95,
          scale = 0.10999999940395,
          tint_a = 85,
          tint_b = 210,
          tint_g = 242,
          tint_r = 255,
          x = 1716,
          y = -513
        },
        {
          id = 66,
          name = "CHARACTER",
          node_type = "SLOT",
          plax_flags = 119,
          posedef = "sit_at_table_back",
          preview_agent = "ROOK",
          priority = 2,
          scale = 0.68000000715256,
          x = -386,
          y = -755
        }
      },
      name = "FG",
      plax = 98.764999389648,
      plax_flags = 127
    }
  },
  mod_id = "DemocraticRace",
  night_colour = "interior_night",
  plax = 150
}